env:
  browser: true
  es6: true
extends:
  - 'plugin:@typescript-eslint/recommended'
  - prettier
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
  - prettier
  - react
  - react-hooks
root: true
rules:
  '@typescript-eslint/no-unused-vars':
    - 'warn' # or "error"
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  prettier/prettier: error
